from base.tests.BaseTest import BaseTestClass
from base.tests.AuthTest import AuthTestClass
from base.tests.UserTest import UserTestClass
from base.tests.EventTest import EventTestClass
from base.tests.EventCommentTest import EventCommentTestClass
from base.tests.EventMemberTest import EventMemberTestClass
from base.tests.NotificationTest import NotificationTestClass
from base.tests.FriendTest import FriendTestClass
from base.tests.FeedbackTest import FeedbackTestClass
from base.tests.ActivityLogTest import ActivityLogTestClass
