# Generated by Django 4.0.1 on 2022-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_eventmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, default=0, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
