# Generated by Django 4.0.1 on 2022-11-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_uservote'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
