# Generated by Django 4.0.1 on 2022-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_event_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
