# Generated by Django 4.1.2 on 2022-12-01 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 8, 13, 53, 646719)),
        ),
    ]
