# Generated by Django 4.1.2 on 2022-12-01 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 13, 8, 49, 298302)),
        ),
    ]
