# Generated by Django 4.0.1 on 2022-12-02 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_event_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 23, 32, 5, 77144)),
        ),
    ]
