# Generated by Django 4.0.1 on 2023-08-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userextend',
            name='isEmailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
