# Generated by Django 4.0.1 on 2023-08-03 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_emailverify_userextend_isemailverified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverify',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='emailverify',
            name='email',
        ),
        migrations.AddField(
            model_name='emailverify',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
