# Generated by Django 4.0.1 on 2023-09-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_event_details_alter_eventcomment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
