# Generated by Django 4.0.1 on 2023-09-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_feedback_category_feedback_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
