name: Deploy CDK Stack

on:
  push:
    branches:
      # - main

permissions:
  id-token: write   # This is required for requesting the JWT (https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install -g aws-cdk
        cd cdk
        npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::311141545056:role/OIDC-github-actions
        aws-region: ap-southeast-2

    - name: Deploy CDK stack
      run: |
        cd cdk
        cdk deploy --require-approval never